// Bundles the importer into the one file Supabase uploads.
//
// The scrapers share `src/lib` with the app — the same chord parser, the same
// Hebrew text matching, tested once in smoke/logic.mjs. The Edge Function
// deploy only uploads what sits under supabase/functions, so instead of
// keeping a second copy of those modules there, we flatten the whole graph
// into supabase/functions/import/index.ts on the way out. It is generated,
// gitignored, and rebuilt by `npm run fn:deploy`.
import { build } from 'esbuild';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { statSync } from 'node:fs';

const here = dirname(fileURLToPath(import.meta.url));
const app = resolve(here, '..');
const out = resolve(app, 'supabase/functions/import/index.ts');

await build({
  entryPoints: [resolve(app, 'server/edge.entry.js')],
  outfile: out,
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  /* Deno supplies these; nothing else is needed at runtime. */
  banner: { js: '// Generated by `npm run fn:build` — edit app/server/*.js instead.' }
});

console.log(`bundled → supabase/functions/import/index.ts (${(statSync(out).size / 1024).toFixed(1)} kB)`);
